# Generated by Django 5.1.3 on 2025-03-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
            ],
        ),
    ]
